# Generated by Django 3.1.7 on 2021-03-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='网站名称')),
                ('description', models.CharField(max_length=100, verbose_name='网站描述')),
                ('logo', models.URLField(blank=True, verbose_name='网站LOGO')),
                ('link', models.URLField(verbose_name='网站地址')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否显示')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
            ],
        ),
    ]
